[build-system]
requires = [
  "hatchling >= 1.26",
  "hatch-requirements-txt >= 0.4.1"
]
build-backend = "hatchling.build"

[project]
name = "tize"
description = "Templatize a project"
keywords = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
  {name = "Jeremy Watkins", email = "DevOpsJeremy@gmail.com"}
]
maintainers = [
  {name = "Jeremy Watkins", email = "DevOpsJeremy@gmail.com"}
]

dynamic = [
  "dependencies",
  "version"
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://example.com/docs"
Repository = "https://github.com/DevOpsJeremy/tize"
Issues = "https://github.com/DevOpsJeremy/tize/issues"
Changelog = "https://github.com/DevOpsJeremy/tize/blob/main/CHANGELOG.md"

# [project.scripts]
# tize = "tize.cli:tize"

[tool.hatch.version]
path = "src/tize/__init__.py"

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
include = ["tize"]

[tool.hatch.build.targets.sdist]
include = ["tize", "/requirements.txt"]

[tool.hatch.metadata.hooks.requirements_txt]
filename = "requirements.txt"

[tool.pytest]
strict = true
# TODO: Remove --capture=no
addopts = ["--tb=line", "-rN", "-W", "ignore", "--junit-xml", "pytest.junit.xml", "--github-report", "--capture=no"]
junit_suite_name = "tize"

markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]


[tool.ruff]
output-format = "github"
